### ISSUE TITLE
Epic: Implement site-wide fix

### ISSUE THREAD

**Issue by foreign1** [foreign1/powerdeck#18]
- [ ] #21
  - [x] Home: remove watermarked image
  - [x] Home: swap out one green gen with the orange
- [ ] #19
- [ ] #20
  - [x] Services: in the equipment maintenance section, intermix images of generators and payloaders
  - [x] Services: move the parts (gallons e.t.c.) to the first frame of the image gallery
  - [x] Services: using the freshly provided `parts` images, create a mix of parts and whole goods in the corresponding section
  - [x] Services: add Akanmu's picture to the training section
  - [x] Services: remove the watermarked images
  - [x] Services: use one blue gen
  - [x] Services: find replacement for one of the watermarked images
